id: I4055CAA5
legacy_id: P006771
ocr_import_info:
  bdrc_scan_id: W2CZ7927
  source: bdrc
  ocr_info:
    timestamp: '2020-03-25T18:29:44'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T15:29:50.156942+00:00'
last_modified: 2022-09-02 23:29:57.735643
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W2CZ7927
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW2CZ7927
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: བྲག་ཕུག་པའི་རྣམ་ཐར།
  author: རི་ཁྲོད་པ་བློ་གྲོས་བརྟན་པ།
statistics:
  ocr_word_mean_confidence_index: 0.6095854933614905
  ocr_word_median_confidence_index: 0.6100000143051147
quality: null
bases:
  I1KG3416:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG3416
      total_pages: 18
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG3416.txt
    statistics:
      ocr_word_median_confidence_index: 0.6100000143051147
      ocr_word_mean_confidence_index: 0.6095854933614905
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
