id: I4055CAA5
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T18:29:54+00:00'
last_modified: '2022-06-08T06:44:43.118680+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2CZ7927
  title: བྲག་ཕུག་པའི་རྣམ་ཐར་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    CC2A:
      image_group_id: I1KG3416
      title: ''
      total_pages: 18
      order: 1
      base_file: CC2A.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
